// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0F7SN_q6xaYmNhAyLrymloK6YJ7ODFQ',
    appId: '1:894808268451:web:5ba97a014a1795abe26916',
    messagingSenderId: '894808268451',
    projectId: 'pnrkuru-c5b17',
    authDomain: 'pnrkuru-c5b17.firebaseapp.com',
    storageBucket: 'pnrkuru-c5b17.appspot.com',
    measurementId: 'G-CNXXRW8VXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXJ95koWOiFmxdY56nF8oEoOGed-75Akc',
    appId: '1:894808268451:android:83aa8e89610fae39e26916',
    messagingSenderId: '894808268451',
    projectId: 'pnrkuru-c5b17',
    storageBucket: 'pnrkuru-c5b17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmq5lFAi9RJ5GC2N5w_BrcNA8SEVit400',
    appId: '1:894808268451:ios:3681270f371e909be26916',
    messagingSenderId: '894808268451',
    projectId: 'pnrkuru-c5b17',
    storageBucket: 'pnrkuru-c5b17.appspot.com',
    iosClientId: '894808268451-tjl02nvgipmj4q5dkb00nli856g7411n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ankprj',
  );
}
